# fly.toml app configuration file generated for cv-converter on 2024-02-02T12:17:12-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cv-converter'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
